Brazilian_ecommerce_datasets:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: Enter your account
      user: Enter your username
      password: Enter your password
      role: Enter your role
      database: Enter your database
      warehouse: Enter your warehouse
      schema: Enter your Schema
      threads: 1
      client_session_keep_alive: False

