Brazilian_ecommerce_datasets:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: FFMEHDX-KC04426
      user: RINKUAAHI
      password: Security@12345
      role: ACCOUNTADMIN       # or another role if applicable
      database: BRAZILIAN_ECOMMERCE
      warehouse: TRANSFORMING
      schema: RAW
      threads: 1
      client_session_keep_alive: False

