
version: 2

sources:
  - name: raw
    database: BRAZILIAN_ECOMMERCE
    schema: RAW
    tables:
      - name: customers
      - name: geolocations
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: orders
      - name: product_category
      - name: products
      - name: sellers